### ISSUE TITLE
query multiple values

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/zooma#31]
How do you query for multiple values e.g origintissue:lung and tumortype:metastatic. The following doesn't seem to work

http://scrappy:8081/recommendations/search?propertyType=origintissue&propertyType=tumortype&propertyValue=metastatic&propertyValue=lung&target=samplediagnosis

**Comment by warrenread** [comment]
Required editing the query string builder: rather building the query independently of the containing the Criteria object (by simplistically inserting " OR " as a separator between list elements), the query now uses Criteria class methods to build the query string (mostly using the _and_ method). This no longer throws an error with multiple propertyType/propertyValue parameters; moreover, it works as intended.
