### ISSUE TITLE
Add BioSamples as datasource

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/zooma#39]
"Venous malformation" is mapped to 
http://identifiers.org/medgen/C2937220 in ZOOMA. The mapping seems 
wrong, since Medgen/C2937220 is not an ontology term. Please find the 
new mapping attached.

See the original ticket logged on RT https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=390419

**Comment by henrietteharmse** [comment]
Biosamples should be added as a new datasource in Zooma. Then they can update their mappings similar to how atlas do.

**Comment by FuqiX** [comment]
@mcourtot We can discuss how and when to add BioSamples
