### ISSUE TITLE
Deploying with Docker readme update suggestions 

### ISSUE THREAD

**Issue by uuo118** [EBISPOT/zooma#80]
When pulling the zooma image as suggested by the readme

```
docker run -d --name zooma -p 8009:8080 -v zooma-config:/root/.zooma/config ebispot/zooma:latest`
```
Docker will outputs the following

```
docker: Error response from daemon: manifest for ebispot/zooma:latest not found: manifest unknown: manifest unknow
```
Therefore, it is necessary to list all the tags for the repo. I was able to find the tags via `wget -q https://registry.hub.docker.com/v1/repositories/ebispot/zooma/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'` and pull the image with 'main' and 'stable' tags.

Also if using `docker run` with `-p 8009:8080` option ZOOMA will be accessible via 8009 port at `http://localhost:8009`, rather than 'http://localhost:8080` as the readme suggest.

**Comment by udp** [comment]
Thanks for reporting this. I'll update the readme!
