### ISSUE TITLE
Internal Server Errors from Zooma API

### ISSUE THREAD

**Issue by apriltuesday** [EBISPOT/zooma#94]
We're seeing quite a few 500 Internal Server Errors coming from the Zooma API since yesterday afternoon.  It doesn't seem to be consistently happening for any particular request, though the frequency of 500s seems even greater this morning.

Some example URLs that have failed:
* https://www.ebi.ac.uk/spot/zooma/v2/api/services/annotate?propertyValue=recurrent%20bacterial%20skin%20infections&filter=required:%5Bcttv,eva-clinvar,clinvar-xrefs,gwas%5D,ontologies:%5Befo,ordo,hp,mondo%5D,preferred:%5Beva-clinvar,cttv,gwas,clinvar-xrefs%5D
* https://www.ebi.ac.uk/spot/zooma/v2/api/services/annotate?propertyValue=meckel%20syndrome,%20type%206,%20modifier%20of
    * On the other hand, the same query without "modifier of" does seem to work (at least right now): https://www.ebi.ac.uk/spot/zooma/v2/api/services/annotate?propertyValue=meckel%20syndrome,%20type%206

Let me know if there's any other info I can provide or anywhere else I should report this issue.

**Comment by serjoshua** [comment]
Good day!

We encountered issues in one of our instances and fixed it just now. Please do verify on your end.

Thanks.
